[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
x86_64 = "*"
bootloader_api = "0.11.3"
pic8259 = "0.10.3"
pc-keyboard = "0.7.0"
xmas-elf = "0.9.0"
linked_list_allocator = "0.10.5"

kernel-common = { path = "../libraries/kernel-common" }